version: "2"
linters:
  default: none
  enable:
    - cyclop
    - errcheck
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - nestif
    - nilerr
    - nilnil
    - noctx
    - staticcheck
    - unused
    - usestdlibvars
  settings:
    cyclop:
      max-complexity: 10
      skip-tests: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # mergeSlices has cyclomatic complexity of 33, but splitting it into
      # helper functions causes significant performance regression due to
      # preventing Go compiler optimizations (inlining). The function is
      # well-tested and complexity is acceptable for performance-critical code.
      - linters:
          - cyclop
        text: "mergeSlices"
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
