version: "2"
linters:
  default: none
  enable:
    - cyclop
    - errcheck
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - nestif
    - nilerr
    - nilnil
    - noctx
    - staticcheck
    - unused
    - usestdlibvars
  settings:
    cyclop:
      max-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # mergeSlices has cyclomatic complexity of 33, but splitting it into
      # helper functions causes significant performance regression due to
      # preventing Go compiler optimizations (inlining). The function is
      # well-tested and complexity is acceptable for performance-critical code.
      - linters:
          - cyclop
        text: "mergeSlices"
      # buildMetadata is a one-time reflection function that handles many edge cases.
      # Splitting it would make the logic harder to follow.
      - linters:
          - cyclop
        text: "buildMetadata"
      # Test functions naturally have higher complexity due to setup/validation logic.
      # These tests are only slightly over the limit and well-organized.
      - linters:
          - cyclop
        path: "_test\\.go$"
        text: "Test(Merger_NestedStructs|Merger_DeeplyNestedStructs|Merger_CompositePrimaryKey_ThreeFields|Merger_CompositePrimaryKey_MixedTypes)"
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
