apiVersion: v1
kind: ResourceList
items:
  # Base ConfigMap
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: app-base-config
      annotations:
        config.keymerge.io/id: "app-config"
        config.keymerge.io/order: "0"
        config.keymerge.io/final-name: "final-app-config"
    data:
      config.yaml: |
        replicas: 1
        settings:
          debug: false
  # Overlay ConfigMap
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: env-overlay
      annotations:
        config.keymerge.io/id: "app-config"
        config.keymerge.io/order: "100"
    data:
      config.yaml: |
        replicas: 3
        settings:
          env: production
  # Passthrough resource (Deployment)
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-app
    spec:
      replicas: 3
