apiVersion: v1
data:
  app-config.yaml: |
    app:
      name: my-app
      version: 1.0.0
    environment: development
    features:
      enabled:
      - tracing
    logging:
      level: debug
    server:
      port: 3000
      timeout: 30s
    tracing:
      endpoint: http://jaeger:14268/api/traces
      sampling_rate: 0.1
      service_name: my-app
kind: ConfigMap
metadata:
  name: app-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: jaegertracing/jaeger-agent:latest
        name: jaeger-agent
        ports:
        - containerPort: 6831
          protocol: UDP
      - env:
        - name: CONFIG_FILE
          value: /etc/config/app-config.yaml
        image: my-app:latest
        name: app
        volumeMounts:
        - mountPath: /etc/config
          name: config
      volumes:
      - configMap:
          name: app-config
        name: config
